version: '3.8'

services:
  # --- DATABASES ---
  auth-db:
    image: postgres:13
    environment:
      POSTGRES_DB: instagram_auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  post-db:
    image: postgres:13
    environment:
      POSTGRES_DB: instagram_post_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - post_db_data:/var/lib/postgresql/data

  interaction-db:
    image: postgres:13
    environment:
      POSTGRES_DB: instagram_interaction_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - interaction_db_data:/var/lib/postgresql/data

  # --- MICROSERVICES ---
  auth-service:
    build: ./microservices/auth-service
    environment:
      DATABASE_URL: postgres://user:password@auth-db:5432/instagram_auth_db
      JWT_SECRET: secret
      POST_SERVICE_URL: http://post-service:3002
      INTERACTION_SERVICE_URL: http://interaction-service:3003
      PORT: 3001
    depends_on:
      - auth-db
    ports:
      - "3001:3001"

  post-service:
    build: ./microservices/post-service
    environment:
      DATABASE_URL: postgres://user:password@post-db:5432/instagram_post_db
      JWT_SECRET: secret
      AUTH_SERVICE_URL: http://auth-service:3001
      INTERACTION_SERVICE_URL: http://interaction-service:3003
      PORT: 3002
    depends_on:
      - post-db
    ports:
      - "3002:3002"

  interaction-service:
    build: ./microservices/interaction-service
    environment:
      DATABASE_URL: postgres://user:password@interaction-db:5432/instagram_interaction_db
      JWT_SECRET: secret
      AUTH_SERVICE_URL: http://auth-service:3001
      POST_SERVICE_URL: http://post-service:3002
      PORT: 3003
    depends_on:
      - interaction-db
    ports:
      - "3003:3003"

  api-gateway:
    build: ./microservices/api-gateway
    environment:
      PORT: 3000
      AUTH_SERVICE_URL: http://auth-service:3001
      POST_SERVICE_URL: http://post-service:3002
      INTERACTION_SERVICE_URL: http://interaction-service:3003
    depends_on:
      - auth-service
      - post-service
      - interaction-service
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    ports:
      - "3006:3000"
    depends_on:
      - api-gateway

volumes:
  auth_db_data:
  post_db_data:
  interaction_db_data:
